# =============== Appearance ===============
include kittycolors.conf
font_family      MesloLGM Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

# Set window size (in cells) on startup
initial_window_width  100c
initial_window_height 30c

# Rounded corners and padding (good for Wayland compositors)
window_padding_width  0
background_opacity    0.8
window_border_width   1.5pt

# Use system notifications on bell
enable_audio_bell no
visual_bell_duration 0.2

# =============== Scrolling and Clipboard ===============

scrollback_lines 5000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 2.0

# Copy on select,
copy_on_select yes

# Don't close window when shell exits
confirm_os_window_close 0

# =============== Performance ===============

# Enable GPU rendering (default)
repaint_delay 10
input_delay 1
sync_to_monitor yes

# =============== Keybindings (Optional) ===============

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+alt+enter new_window
map ctrl+shift+enter launch --cwd=current

# =============== Cursor trail ===============
cursor_trail 1
cursor_trail_decay 0.2 0.4
cursor_trail_start_threshold 1

# =============== Mouse Behaviour =============
mouse_hide_wait 1.5

# =============== Tabs =================
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
tab_bar_align left
tab_bar_min_tabs 2
tab_bar_margin_width 0.0
tab_bar_margin_height 2.5 1.5
inactive_tab_font_style normal
active_tab_font_style bold

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
