color0                  #32353a
color1                  #ffb4ab
color2                  #bbc7db
color3                  #d8bde4
color4                  #a2c9fe
color5                  #38608f
color6                  #0a60bb
color7                  #e1e2e8
color8                  #8d9199
color9                  #ffcbc5
color10                 #c6d3ea
color11                 #e6c7f4
color12                 #aed0ff
color13                 #4584cf
color14                 #1f7ad9
color15                 #fefefe

cursor                  #e1e2e8
cursor_text_color     #111418
background            #111418
foreground            #e1e2e8
selection_foreground  #c3c6cf
selection_background  #43474e
url_color             #a2c9fe

tab_bar_margin_color    #111418
tab_bar_background      #111418
active_tab_foreground   #00325b
active_tab_background   #a2c9fe
inactive_tab_foreground #c3c6cf
inactive_tab_background #00325b

active_border_color   #a2c9fe
inactive_border_color #43474e
