color0                  #2f3635
color1                  #ffb4ab
color2                  #b0ccc9
color3                  #b0c9e7
color4                  #81d5ce
color5                  #006a65
color6                  #00837c
color7                  #dde4e2
color8                  #889391
color9                  #ffcbc5
color10                 #b8deda
color11                 #bad5f7
color12                 #77ece2
color13                 #00b7ae
color14                 #00b6ad
color15                 #f9fbfa

cursor                  #dde4e2
cursor_text_color     #0e1514
background            #0e1514
foreground            #dde4e2
selection_foreground  #bec9c7
selection_background  #3f4947
url_color             #81d5ce

tab_bar_margin_color    #0e1514
tab_bar_background      #0e1514
active_tab_foreground   #003734
active_tab_background   #81d5ce
inactive_tab_foreground #bec9c7
inactive_tab_background #003734

active_border_color   #81d5ce
inactive_border_color #3f4947
