color0                  #3d3232
color1                  #ffb4ab
color2                  #e6bdba
color3                  #e3c28c
color4                  #ffb3b0
color5                  #904a49
color6                  #b72222
color7                  #f0dedd
color8                  #a08c8b
color9                  #ffcbc5
color10                 #f2cac8
color11                 #f7d092
color12                 #ffbfbd
color13                 #c6615f
color14                 #c74545
color15                 #ffffff

cursor                  #f0dedd
cursor_text_color     #1a1111
background            #1a1111
foreground            #f0dedd
selection_foreground  #d7c1c0
selection_background  #534342
url_color             #ffb3b0

tab_bar_margin_color    #1a1111
tab_bar_background      #1a1111
active_tab_foreground   #571d1e
active_tab_background   #ffb3b0
inactive_tab_foreground #d7c1c0
inactive_tab_background #571d1e

active_border_color   #ffb3b0
inactive_border_color #534342
