themes:
  - name: "EvangelionRed"
    colors:
      - "#000000"
      - "#9A060E"
      - "#980010"
      - "#B40000"
      - "#B31002"
      - "#B30717"
      - "#B42317"
      - "#B82D31"
      - "#B9000C"
      - "#B90005"
      - "#C40000"
      - "#C21B21"
      - "#D40015"
      - "#F00020"
      - "#F70221"
      - "#F3C03D"
