##############################################################################
#fusuma binds for trackpad gestures

swipe:
  3:
    left:
      sendkey: "LEFTMETA+LEFTSHIFT+LEFT" # move to previous workspace
    right:
      sendkey: "LEFTMETA+LEFTSHIFT+RIGHT" # move to next workspace
    up:
      sendkey: "LEFTMETA+R" # open wofi
    down:
      sendkey: "LEFTMETA+LEFTSHIFT+S" # close window

pinch:
  in:
    sendkey: "LEFTCTRL+MINUS" # zoom out
  out:
    sendkey: "LEFTCTRL+EQUAL" # zoom in

threshold:
  swipe: 1.0
  pinch: 0.5

interval:
  swipe: 1.0
  pinch: 1.0
